apiVersion: apps/v1beta1 
kind: Deployment 
metadata:
  name: jmsclient 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jmsclient 
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        name: jmsreceiver
        image: jms-client:1.0
        imagePullPolicy: Never
